### ISSUE TITLE
为什么我在autohotkey下载了2.0版本，exe文件打开是一个文档。

### ISSUE THREAD

**Issue by StephenWu5** [wyagd001/wyagd001.github.io#11]
为什么我在autohotkey下载了2.0版本，exe文件打开是一个文档。？？
可以说一下原因吗

**Comment by wyagd001** [comment]
直接双击运行程序，  默认在主程序目录和我的文档中查找同名脚本文件，如果没有脚本文件，默认打开帮助文件。 将ahk文件类型关联到主程序后，双击ahk脚本文件就可以了。

**Comment by StephenWu5** [comment]
![image](https://user-images.githubusercontent.com/32475322/57357392-6b954d00-71a5-11e9-9585-fd399e6dc8c6.png)
![image](https://user-images.githubusercontent.com/32475322/57357399-6f28d400-71a5-11e9-8a9e-1e5860c31c37.png)
还是不懂，可以教教吗
