### ISSUE TITLE
Win7、IE8 的版本1.1.32.00的chm和html版本显示不正常

### ISSUE THREAD

**Issue by derQiQ** [wyagd001/wyagd001.github.io#15]
Win7、IE8 的版本1.1.32.00的chm和html版本打开显示不正常，【提示对象错误】，然后【目录】列表就丢失了，【搜索】也无法使用输入任意字符出错，不知是否英文原版就不支持IE8？

**Comment by wyagd001** [comment]
1.你先试下英文版是否这样
2.网页脚本都是照搬英文版，如果不支持IE8我也不懂如何处理

PS：ie8？怎么还在用

**Comment by derQiQ** [comment]
感谢回复！

刚试了，用官方英文版CHM，在Win7，IE8下，打开是正常的。
![英文版chm](https://sm.ms/image/5T1eJAX2jniguHo)

就是中文件版的不正常。
![中文版chm](https://sm.ms/image/O5Rf8Mau7ql6oc4)

**Comment by wyagd001** [comment]
应该是 content.js 出了问题，如果是自己编译的chm文件，可以检查下 content.js 文件。我在自己的电脑上chm和网页浏览本地文件都没有问题。

**Comment by derQiQ** [comment]
中文版chm目录问题原因找到了，修正已提交了，中文版chm查询模块问题还在查找原因中。

**Comment by derQiQ** [comment]
英文版chm查询模块在Win7，IE8下本身就有问题，待官方解决了。
