### ISSUE TITLE
GuiControl中的typo

### ISSUE THREAD

**Issue by Leoongithub** [wyagd001/wyagd001.github.io#20]
英文原文：
This is required even if ControlID is a control's associated variable [GuiControl#Remarks](https://www.autohotkey.com/docs/commands/GuiControl.htm#Remarks)

翻译：
即使 ControlID 为控件的关联变量**或 HWND** 这也是必须的 [GuiControl#备注](https://wyagd001.github.io/zh-cn/docs/commands/GuiControl.htm#Remarks)

应去掉`或 HWND `

**Comment by wyagd001** [comment]
谢谢，下次更新时会修正的。
