### ISSUE TITLE
帮助页面在firefox浏览器里，404错误

### ISSUE THREAD

**Issue by kangdalei** [wyagd001/wyagd001.github.io#22]
https://wyagd001.github.io/zh-cn/docs/AutoHotkey.htm

这个页面只有chrome浏览器能正确打开。firefox里显示404错误。难道用了独特技术？

![Snipaste_2020-06-15_13-28-15](https://user-images.githubusercontent.com/31817131/84621089-3e6caf80-af0c-11ea-8c96-d91d8f65b595.jpg)

**Comment by wyagd001** [comment]
自己测试了下在 firefox 中能正常显示啊，你的情况不知道是什么情况

**Comment by kangdalei** [comment]
怀疑是GFW的原因。今天firefox和chrome都彻底打不开了，然后翻梯子，两者都能正常浏览了。
