### ISSUE TITLE
请教一下怎么把文档打包成chm啊？

### ISSUE THREAD

**Issue by yyangdid** [wyagd001/wyagd001.github.io#24]
请教一下怎么把文档打包成chm啊？  望指教 👍

**Comment by wyagd001** [comment]
关于打包chm文件
1.v2主程序 运行 \docs\static\source\build_search.ahk  新建搜索引索
2.安装 HTML Help Workshop
3.编辑 compile_chm.ahk，指定hhc.exe位置，修改这一行    hhc := "N:\资料\autohotkey 帮助\HTML Help Workshop\hhc.exe"
v1主程序  运行compile_chm.ahk自定生成最新的chm文件

**Comment by hana11000** [comment]
好难，不太明白咋获取chm文件。

**Comment by wyagd001** [comment]
1. https://github.com/wyagd001/wyagd001.github.io  code  download zip  下载网页zip包到本地
2. 搜索下载安装 HTML Help Workshop 程序
3. 解压 下载的 zip 包，编辑zh-cn或v2 文件夹中的 compile_chm.ahk，指定hhc.exe位置，修改这一行 hhc := "N:\资料\autohotkey 帮助\HTML Help Workshop\hhc.exe"
4. 运行 compile_chm.ahk 生成chm文件

**Comment by piwawa** [comment]
> 1. https://github.com/wyagd001/wyagd001.github.io  code  download zip  下载网页zip包到本地
> 2. 搜索下载安装 HTML Help Workshop 程序
> 3. 解压 下载的 zip 包，编辑zh-cn或v2 文件夹中的 compile_chm.ahk，指定hhc.exe位置，修改这一行 hhc := "N:\资料\autohotkey 帮助\HTML Help Workshop\hhc.exe"
> 4. 运行 compile_chm.ahk 生成chm文件

可以把最新的2.0.2生成chm发布一下release吗，网上都下载不到绿色的workshop，微软官方下载都404了

**Comment by wyagd001** [comment]
打包好的chm文件下载地址:
v1: https://github.com/wyagd001/RuYi-Ahk/blob/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/AutoHotkeyLCN.chm
https://github.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/AutoHotkeyLCN.chm
v2: https://github.com/wyagd001/RuYi-Ahk/blob/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm
https://github.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm
