### ISSUE TITLE
打包成chm后，缺失Override.htm文件

### ISSUE THREAD

**Issue by FormosaZh** [wyagd001/wyagd001.github.io#28]
![4DLOGZG4LC71FMN) U5S%GB](https://user-images.githubusercontent.com/27438860/144380489-e7ce9b4d-3e9f-4348-ba82-7c5ea51d2cb1.png)

**Comment by wyagd001** [comment]
在 Project.hhp 文件中的 [FILES] 条目下添加两行,下次更新
docs\ChangeLogHelp.htm
docs\misc\Override.htm
