### ISSUE TITLE
请问在线帮助网址，能改成大小写不敏感吗？？

### ISSUE THREAD

**Issue by hyaray** [wyagd001/wyagd001.github.io#29]
比如 https://wyagd001.github.io/v2/docs/commands/InStr.htm
改成小写 https://wyagd001.github.io/v2/docs/commands/instr.htm 就无法打开了。想实现脚本中一键跳转到帮助，被这个卡住了。。

**Comment by wyagd001** [comment]
github 服务器本身支持网址区分大小写, 百度了以下需要做重定向跳转, 而且官网文档网址也是区分大小写的, 所以暂无修改计划.
