### ISSUE TITLE
Replace the Chinese Link in the Sidebar Language Selection

### ISSUE THREAD

**Issue by Ragnar-F** [wyagd001/wyagd001.github.io#3]
Hi, I'm the developer of the sidebar in the English docs.

I would like to replace the outdated Chinese link in the sidebar's language selection with the link to your docs. More specifically, `http://ahkcn.sourceforge.net/docs/` to `https://wyagd001.github.io/zh-cn/docs/`.

What do you think and are you okay with it?

**Comment by wyagd001** [comment]
No problem.welcome.

**Comment by Ragnar-F** [comment]
Lexikos/AutoHotkey_L-Docs#208 will close this issue.
