### ISSUE TITLE
无法使用 chrome的"复制指向突出显示的内容的链接"

### ISSUE THREAD

**Issue by iamqiz** [wyagd001/wyagd001.github.io#31]
如下图, 该功能显示为灰色,没法使用
![image](https://user-images.githubusercontent.com/48077521/164697825-ed645270-6ca5-4375-b985-e20a80f31a4d.png)

**Comment by iamqiz** [comment]
貌似是因为 正文是放在iframe里导致的
![image](https://user-images.githubusercontent.com/48077521/164965453-2da28688-2e29-4914-a8bf-356d660f5601.png)

**Comment by wyagd001** [comment]
暂时无解
