### ISSUE TITLE
关于热字串的教程问题.

### ISSUE THREAD

**Issue by luminous030** [wyagd001/wyagd001.github.io#39]
> 这两个例子的区别在于, 当你按下 Ctrl+J 时, 热键将会触发, 而热字串会将你输入的 "ftw" 转换为 "Free the whales".

在上面这个例子中, 是不是应该说明下输入"ftw"以后需要按非字母/数字键来激活?

**Comment by wyagd001** [comment]
官方没写, 翻译的时候也就跟着没写. 不过这是初学者向导就怎么简单怎么来, 加上的话就会显得复杂.
