### ISSUE TITLE
v2版FileInstall函数的Source参数介绍中有一个翻译错误

### ISSUE THREAD

**Issue by FreyLee** [wyagd001/wyagd001.github.io#42]
v2版英文原文: This parameter must be a quoted literal string (not a variable or any other expression)
v1版英文原文: The file name must not contain double quotes, variable references (e.g. %A_ProgramFiles%), or wildcards.
v2版中文翻译: 文件名不能包含双引号或通配符.

1. 没有使用v2版相应的描述文本
2. 翻译描述中缺少了**变量引用**

**Comment by wyagd001** [comment]
v2 版相关语句已修改, 谢谢.
