### ISSUE TITLE
SetTimer 第二个示例缺少一个空格.

### ISSUE THREAD

**Issue by skelet8801** [wyagd001/wyagd001.github.io#46]
https://wyagd001.github.io/v2/docs/lib/SetTimer.htm

错误的地方 :
SetTimer, 0  ; 即此处计时器关闭自己.

"SetTimer," 中间应该有一个空格 , 应该是这样的: "SetTimer ,", 否则运行错误.

**Comment by wyagd001** [comment]
谢谢支持, 下次同步时修正.

**Comment by wyagd001** [comment]
谢谢, 下次同步时修正.
