### ISSUE TITLE
感谢+请教站点生成工具

### ISSUE THREAD

**Issue by iikkjjll** [wyagd001/wyagd001.github.io#47]
您好，非常感谢您做的工作，另外还想请教一下，这个网站是用什么工具生成的？这个和我用过的vitepress等工具不太一样，我很喜欢这个自带的搜索功能，也在网上找了许久未果，也询问了NewBing和ChatGPT，说的是像sphinx生成的，但我看了下跟这个网站也不一样，不知道是不是主题的原因，希望您告知一下，谢谢啦！

**Comment by wyagd001** [comment]
如果你指的是Ahk帮助文件中的搜索功能, 那我也不知道是如何实现的. 因为我对 Js 脚本也不太熟悉, 其中的搜索功能我也是从英文原版照搬过来而以. 不能帮到你啦.
