### ISSUE TITLE
翻译错误: WinTitle 默认匹配模式

### ISSUE THREAD

**Issue by stonereese** [wyagd001/wyagd001.github.io#58]
WinActive, WinExist 等相关函数中, 在参数小节里的末尾: 
> 默认情况下, 窗口标题必须以指定的 WinTitle 或 ExcludeTitle 开头才能匹配, 除非使用 [SetTitleMatchMode](https://wyagd001.github.io/v2/docs/lib/SetTitleMatchMode.htm) 进行更改.    

在英文中为:   
> By default, a window title can contain WinTitle or ExcludeTitle anywhere inside it to be a match, unless changed with [SetTitleMatchMode](https://www.autohotkey.com/docs/v2/lib/SetTitleMatchMode.htm).   

根据 [SetTitleMatchMode](https://www.autohotkey.com/docs/v2/lib/SetTitleMatchMode.htm). 可知, 默认 WinTitle 采用包含模式, 而不是开头匹配模式, 英文的说法是正确的.

**Comment by wyagd001** [comment]
谢谢,已经修正.
