### ISSUE TITLE
请问大师您使用哪款软件编译CHM的？

### ISSUE THREAD

**Issue by xurdy** [wyagd001/wyagd001.github.io#62]
大师您好，请问您是使用哪款软件编译CHM的？我感觉你编译的那个AHK.chm和其他人编译的chm样式不一样。

我非常想知道您是如何办到的。希望不吝赐教，谢谢

![PixPin_2024-11-09_23-11-27](https://github.com/user-attachments/assets/4e333292-96d3-4f58-bb2f-ee95616e3821)

**Comment by wyagd001** [comment]
编译 chm 文件说明

安装 HTML Help Workshop(hhc.exe)
compile_chm.ahk 文件中修改变量 hhc 的值为 hhc.exe 程序的路径
使用 v1 U版 运行 compile_chm.ahk
更新搜索列表 需用 v2 运行 build_search.ahk

PS. 编译好的 chm 文件下载地址: https://github.com/wyagd001/RuYi-Ahk/blob/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm
https://github.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm
下载链接: [github](https://raw.githubusercontent.com/wyagd001/RuYi-Ahk/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm) 或 [gitee](https://gitee.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm)

**Comment by xurdy** [comment]
> 编译 chm 文件说明
> 
> 安装 HTML Help Workshop(hhc.exe) compile_chm.ahk 文件中修改变量 hhc 的值为 hhc.exe 程序的路径 使用 v1 U版 运行 compile_chm.ahk 更新搜索列表 需用 v2 运行 build_search.ahk
> 
> PS. 编译好的 chm 文件下载地址: https://github.com/wyagd001/RuYi-Ahk/blob/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm https://github.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm 下载链接: [github](https://raw.githubusercontent.com/wyagd001/RuYi-Ahk/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm) 或 [gitee](https://gitee.com/wyagd001/RuYi-Ahk/raw/main/%E5%BC%95%E7%94%A8%E7%A8%8B%E5%BA%8F/2.0/AutoHotkey2.0.chm)

请问对编译的素材有什么要求吗？比如必须是独立的HTML文件之类的？

**Comment by wyagd001** [comment]
这是脚本自动编译的,脚本也是国外友人编写的,我对 hhc.exe 这款软件也没有手动使用过,不能帮到你了.

**Comment by xurdy** [comment]
> 这是脚本自动编译的,脚本也是国外友人编写的,我也没有使用 hhc.exe 这款软件编译过其他chm文件,不能帮到你了. 编译命令的核心是 hhc.exe Project.hhp, 所以你研究下 Project.hhp 和 Index.hhk 文件看下是否有帮助. 另外ahk的chm文件的界面(包括目录树),语法高亮和搜索都是网页和js脚本控制的,都是只适合ahk的,所以如果要移植到其他网页资料,还需要对网页和js语言有所了解,才能适配到其他chm文件的编译.

好的，谢谢大神指点
