### ISSUE TITLE
v2文档有几处未翻译

### ISSUE THREAD

**Issue by Summer1Solstice** [wyagd001/wyagd001.github.io#63]
[函数对象](https://github.com/wyagd001/wyagd001.github.io/blob/2d05b899e8530ff10cbfc2e26ba4e298ff222d6a/v2/docs/misc/Functor.htm#L42)

> HasMethod(Value) 适用于所有的 AutoHotkey 值和对象, 并且不能被重写, 但如果不能确定 Call 方法的存在, 则返回 false. An exception is thrown if Value is a ComObject.

[变量和表达式 | 内置变量 | 脚本属性 A_ScriptFullPath](https://github.com/wyagd001/wyagd001.github.io/blob/2d05b899e8530ff10cbfc2e26ba4e298ff222d6a/v2/docs/Variables.htm#L436)

> 如果脚本文字是从标准输入中读取的而不是从文件中读取的, this variable contains an asterisk (*).

[#HotIf  | 基本操作](https://github.com/wyagd001/wyagd001.github.io/blob/2d05b899e8530ff10cbfc2e26ba4e298ff222d6a/v2/docs/lib/_HotIf.htm#L39)

> The #HotIf directive only affects hotkeys and hotstrings created via the double-colon syntax, such as ^!c:: or ::btw::. For hotkeys and hotstrings created via the Hotkey or Hotstring function, use the HotIf function.

**Comment by wyagd001** [comment]
已经翻译好了
